[tool.poetry]
name = "teleddns-server"
version = "0.2.0"
description = "DDNS API server - Django Edition"
authors = ["Tomas Hlavacek <tmshlvck@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0"
djangorestframework = "^3.15"
django-environ = "^0.11"
requests = "^2.31"
uvicorn = "^0.30"
drf-spectacular = "^0.28.0"

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.3"
black = "^24.3"
isort = "^5.13"
flake8 = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
teleddns-server = "teleddns_server.manage:main"

[tool.isort]
profile = "black"
skip_gitignore = true
force_single_line = true
line_length = 120

[tool.black]
line-length = 120
