# Generated by Django 5.2.4 on 2025-08-21 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("master", "Master"), ("slave", "Slave")],
                        help_text="Role of this server for the zone",
                        max_length=10,
                    ),
                ),
                (
                    "config_dirty",
                    models.BooleanField(default=False, help_text="Server configuration for this zone needs update"),
                ),
                (
                    "config_dirty_since",
                    models.DateTimeField(blank=True, help_text="When config was marked dirty", null=True),
                ),
                (
                    "content_dirty",
                    models.BooleanField(
                        default=False, help_text="Zone content needs to be synchronized (master servers only)"
                    ),
                ),
                (
                    "content_dirty_since",
                    models.DateTimeField(
                        blank=True, help_text="When content was marked dirty (master servers only)", null=True
                    ),
                ),
                (
                    "last_sync_time",
                    models.DateTimeField(blank=True, help_text="Last successful synchronization time", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="zone_servers", to="manager.server"
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="zone_servers", to="manager.zone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone Server",
                "verbose_name_plural": "Zone Servers",
                "unique_together": {("zone", "server", "role")},
            },
        ),
    ]
