# Generated by Django 5.2.4 on 2025-08-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_add_zoneserver"),
    ]

    operations = [
        # Remove fields from Zone model
        migrations.RemoveField(
            model_name="zone",
            name="master_config_dirty",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="master_config_dirty_since",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="master_server",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="slave_servers",
        ),

        # Remove old models
        migrations.DeleteModel(
            name="SlaveOnlyZone",
        ),
        migrations.DeleteModel(
            name="SlaveOnlyZoneServerStatus",
        ),
        migrations.DeleteModel(
            name="ZoneServerStatus",
        ),
    ]
