# Generated by Django 5.2.4 on 2025-08-06 08:34

from django.db import migrations


def migrate_soa_forward(apps, schema_editor):
    """Create SOA records from existing Zone SOA fields"""
    Zone = apps.get_model('manager', 'Zone')
    SOA = apps.get_model('manager', 'SOA')

    for zone in Zone.objects.all():
        # Create SOA record from zone's SOA fields
        SOA.objects.create(
            zone=zone,
            name=zone.soa_name,
            rrclass=zone.soa_class,
            ttl=zone.soa_ttl,
            mname=zone.soa_mname,
            rname=zone.soa_rname,
            serial=zone.soa_serial,
            refresh=zone.soa_refresh,
            retry=zone.soa_retry,
            expire=zone.soa_expire,
            minimum=zone.soa_minimum
        )


def migrate_soa_reverse(apps, schema_editor):
    """Remove SOA records and restore data to Zone model"""
    Zone = apps.get_model('manager', 'Zone')
    SOA = apps.get_model('manager', 'SOA')

    for soa in SOA.objects.all():
        # Update zone with SOA data before deleting
        zone = soa.zone
        zone.soa_name = soa.name
        zone.soa_class = soa.rrclass
        zone.soa_ttl = soa.ttl
        zone.soa_mname = soa.mname
        zone.soa_rname = soa.rname
        zone.soa_serial = soa.serial
        zone.soa_refresh = soa.refresh
        zone.soa_retry = soa.retry
        zone.soa_expire = soa.expire
        zone.soa_minimum = soa.minimum
        zone.save()

    # Delete all SOA records
    SOA.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_add_soa_and_slave_only_zone"),
    ]

    operations = [
        migrations.RunPython(migrate_soa_forward, migrate_soa_reverse),
    ]
