# Generated by Django 5.2.4 on 2025-08-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_remove_old_zone_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zoneserver",
            name="content_dirty",
        ),
        migrations.RemoveField(
            model_name="zoneserver",
            name="content_dirty_since",
        ),
    ]
