# Generated by Django 5.2.4 on 2025-08-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_migrate_soa_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zone",
            name="soa_class",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="soa_expire",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="soa_minimum",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="soa_mname",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="soa_name",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="soa_refresh",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="soa_retry",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="soa_rname",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="soa_serial",
        ),
        migrations.RemoveField(
            model_name="zone",
            name="soa_ttl",
        ),
    ]
